export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
// export const UPDATE_CATEGORY = "UPDATE_CATEGORY";    // AA ME REDUCER MATE BANAITI.
export const SHOW_SLIDEBAR = "SHOW_SLIDEBAR";
export const ADD_NOTE = "ADD_NOTE";
export const SEARCH_CATEGORY = "SEARCH_CATEGORY";
// export const UPDATE_NOTE = "UPDATE_NOTE";
export const REMOVE_NOTE = "REMOVE_NOTE";

// aahi thi backend ma connect karyu te badha type che..
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING"; // aa vastu mare action ma karavni jarur nathi kem ke jyre get call vagse tyre aa call thai jase..

export const POST_CATEGORIES = "POST_CATEGORIES";
export const POST_CATEGORIES_LOADING = "POST_CATEGORIES_LOADING";
export const POST_CATEGORIES_SUCCESS = "POST_CATEGORIES_SUCCESS";
export const POST_CATEGORIES_ERROR = "POST_CATEGORIES_ERROR";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_LOADING = "UPDATE_CATEGORY_LOADING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";

export const GET_NOTES = "GET_NOTES";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_ERROR = "GET_NOTES_ERROR";
export const GET_NOTES_LOADING = "GET_NOTES_LOADING";

export const POST_NOTE = "POST_NOTE";
export const POST_NOTE_SUCCESS = "POST_NOTE_SUCCESS";
export const POST_NOTE_ERROR = "POST_NOTE_ERROR";
export const POST_NOTE_LOADING = "POST_NOTE_LOADING";

export const UPDATE_NOTE = "UPDATE_NOTE";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_ERROR = "UPDATE_NOTE_ERROR";
export const UPDATE_NOTE_LOADING = "UPDATE_NOTE_LOADING";

export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR";
export const DELETE_NOTE_LOADING = "DELETE_NOTE_LOADING";

export const CLEAR_ERROR = "CLEAR_ERROR";
// export const
